sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t mosaadm/docker-react -f Dockerfile.dev .

script:
  - docker run CI=true mosaadm/docker-react npm run test -- --coverage